[package]
name = "rgb-schemata"
version = "0.11.0-beta.4"
description = "Collection of the official RGB smart contract schemata"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-schemata"
rust-version = "1.69.0" # Due to TOML dependency in amplify crate
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
amplify = "4.5.1"
strict_encoding = "2.7.0"
strict_types = "2.7.0"
aluvm = "0.11.0-beta.2"
bp-core = "0.11.0-beta.3"
rgb-std = { version = "0.11.0-beta.4", features = ["serde", "fs"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10.8"

[dev-dependencies]
chrono = "0.4.31"
serde_yaml = "0.9.27"

[features]
all=[]

[patch.crates-io]
strict_encoding = { git = "https://github.com/strict-types/strict-encoding", branch = "refactor/io" }
strict_types = { git = "https://github.com/strict-types/strict-types", branch = "refactor/io" }
commit_verify = { git = "https://github.com/LNP-BP/client_side_validation", branch = "v0.11" }
bp-consensus = { git = "https://github.com/BP-WG/bp-core", branch = "v0.11" }
bp-dbc = { git = "https://github.com/BP-WG/bp-core", branch = "v0.11" }
bp-seals = { git = "https://github.com/BP-WG/bp-core", branch = "v0.11" }
bp-core = { git = "https://github.com/BP-WG/bp-core", branch = "v0.11" }
bp-invoice = { git = "https://github.com/BP-WG/bp-std", branch = "v0.11" }
aluvm = { git = "https://github.com/AluVM/rust-aluvm", branch = "v0.11" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "vesper" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-std", branch = "v0.11" }
