[package]
name = "rgb-schemata"
version = "0.10.0-beta.1"
description = "Collection of the official RGB smart contract schemata"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/RGB-WG"
repository = "https://github.com/RGB-WG/rgb-schemata"
rust-version = "1.67"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
amplify = "4.0.0"
strict_encoding = "2.5.0"
strict_types = "1.5.0"
aluvm = "0.10.2"
bp-core = "0.10.5"
rgb-std = { version = "0.10.2", features = ["serde", "fs"] }
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.7"

[features]
all=[]

[patch.crates-io]
rgb-core = { git = "https://github.com/crisdut/rgb-core", branch = "release/bmc-v0.6-rc6" }
rgb-std = { git = "https://github.com/crisdut/rgb-wallet", branch = "release/bmc-v0.6-rc6" }
